version: "2.3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: gotravel-be
    depends_on:
      - mongo
    restart: always
    environment:
      - DB=mongo
    networks:
      - gtravel
    ports:
      - 8888:8888

  mongo:
    image: 'bitnami/mongodb:3.6'
    volumes: ["mongodb_data:/bitnami"]
    restart: always
    networks:
      - gtravel
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:0.45.0
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    restart: always
    networks:
      - gtravel
    ports:
      - "8889:8081"

volumes:
  mongodb_data:

networks:
  gtravel:
