apiVersion: v1
kind: Namespace
metadata:
  name: go-travel

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: go-travel
  name: go-travel-db
spec:
  selector:
    matchLabels:
      type: db
      service: go-travel
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: db
        service: go-travel
        vendor: MongoLabs
    spec:
      containers:
      - name: db
        image: bitnami/mongodb:3.6

---

apiVersion: v1
kind: Service
metadata:
  namespace: go-travel
  name: go-travel-db
spec:
  ports:
  - port: 27017
  selector:
    type: db
    service: go-travel-db

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-travel-be
  namespace: go-travel
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /travel
        backend:
          serviceName: go-travel-be
          servicePort: 8888

---
kind: Service
apiVersion: v1
metadata:
  name: go-travel-be
  namespace: go-travel
spec:
  ports:
   - port: 8888
  selector:
    app: go-travel-be

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-travel-be
  namespace: go-travel
  labels:
    app: go-travel
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: go-travel-be
    spec:
      containers:
        - name: backend
          image: caladreas/go-travel
          env:
          - name: DB
            value: go-travel-db
          readinessProbe:
              httpGet:
                path: /trips
                port: 8888
              periodSeconds: 1
          livenessProbe:
              httpGet:
                path: /trips
                port: 8888

